"""create_xitique_tables

Revision ID: 83ccc671f751
Revises: e68629c68c60
Create Date: 2026-09-25 14:40:05.262689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ccc671f751'
down_revision: Union[str, None] = 'e68629c68c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xitique_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('MONETARY', 'PRODUCTS', name='xitiquetype'), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=True),
    sa.Column('contribution_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('period', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', name='xitiqueperiod'), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('FIXED', 'LOTTERY', name='xitiqueordertype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'SUSPENDED', name='xitiquestatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xitique_groups_company_id'), 'xitique_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_xitique_groups_id'), 'xitique_groups', ['id'], unique=False)
    op.create_table('xitique_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('receive_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEFAULTED', 'REMOVED', name='memberstatus'), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['xitique_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xitique_members_group_id'), 'xitique_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_xitique_members_id'), 'xitique_members', ['id'], unique=False)
    op.create_table('xitique_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'LATE', 'WAIVED', name='contributionstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MPESA', 'TRANSFER', name='paymentmethod'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['xitique_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['xitique_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xitique_contributions_group_id'), 'xitique_contributions', ['group_id'], unique=False)
    op.create_index(op.f('ix_xitique_contributions_id'), 'xitique_contributions', ['id'], unique=False)
    op.create_index(op.f('ix_xitique_contributions_member_id'), 'xitique_contributions', ['member_id'], unique=False)
    op.create_table('xitique_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('amount_delivered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', name='deliverystatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['xitique_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['xitique_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xitique_deliveries_group_id'), 'xitique_deliveries', ['group_id'], unique=False)
    op.create_index(op.f('ix_xitique_deliveries_id'), 'xitique_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_xitique_deliveries_member_id'), 'xitique_deliveries', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xitique_deliveries_member_id'), table_name='xitique_deliveries')
    op.drop_index(op.f('ix_xitique_deliveries_id'), table_name='xitique_deliveries')
    op.drop_index(op.f('ix_xitique_deliveries_group_id'), table_name='xitique_deliveries')
    op.drop_table('xitique_deliveries')
    op.drop_index(op.f('ix_xitique_contributions_member_id'), table_name='xitique_contributions')
    op.drop_index(op.f('ix_xitique_contributions_id'), table_name='xitique_contributions')
    op.drop_index(op.f('ix_xitique_contributions_group_id'), table_name='xitique_contributions')
    op.drop_table('xitique_contributions')
    op.drop_index(op.f('ix_xitique_members_id'), table_name='xitique_members')
    op.drop_index(op.f('ix_xitique_members_group_id'), table_name='xitique_members')
    op.drop_table('xitique_members')
    op.drop_index(op.f('ix_xitique_groups_id'), table_name='xitique_groups')
    op.drop_index(op.f('ix_xitique_groups_company_id'), table_name='xitique_groups')
    op.drop_table('xitique_groups')
    # ### end Alembic commands ###
