"""create_savings_tables

Revision ID: bbc737701755
Revises: 83ccc671f751
Create Date: 2026-09-25 14:45:07.840884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc737701755'
down_revision: Union[str, None] = '83ccc671f751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cycle_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='savingsgroupstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_groups_company_id'), 'savings_groups', ['company_id'], unique=False)
    op.create_index(op.f('ix_savings_groups_id'), 'savings_groups', ['id'], unique=False)
    op.create_table('savings_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('total_deposited', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_borrowed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_repaid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='savingsmemberstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['savings_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_members_group_id'), 'savings_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_savings_members_id'), 'savings_members', ['id'], unique=False)
    op.create_table('savings_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deposited_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MPESA', 'TRANSFER', name='savingspaymentmethod'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['savings_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['savings_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_deposits_group_id'), 'savings_deposits', ['group_id'], unique=False)
    op.create_index(op.f('ix_savings_deposits_id'), 'savings_deposits', ['id'], unique=False)
    op.create_index(op.f('ix_savings_deposits_member_id'), 'savings_deposits', ['member_id'], unique=False)
    op.create_table('savings_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_repayable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_repaid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursed_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REPAID', 'DEFAULTED', name='savingsloanstatus'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['savings_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['savings_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_loans_group_id'), 'savings_loans', ['group_id'], unique=False)
    op.create_index(op.f('ix_savings_loans_id'), 'savings_loans', ['id'], unique=False)
    op.create_index(op.f('ix_savings_loans_member_id'), 'savings_loans', ['member_id'], unique=False)
    op.create_table('savings_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('repaid_at', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MPESA', 'TRANSFER', name='savingspaymentmethod'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['savings_loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_repayments_id'), 'savings_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_savings_repayments_loan_id'), 'savings_repayments', ['loan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_repayments_loan_id'), table_name='savings_repayments')
    op.drop_index(op.f('ix_savings_repayments_id'), table_name='savings_repayments')
    op.drop_table('savings_repayments')
    op.drop_index(op.f('ix_savings_loans_member_id'), table_name='savings_loans')
    op.drop_index(op.f('ix_savings_loans_id'), table_name='savings_loans')
    op.drop_index(op.f('ix_savings_loans_group_id'), table_name='savings_loans')
    op.drop_table('savings_loans')
    op.drop_index(op.f('ix_savings_deposits_member_id'), table_name='savings_deposits')
    op.drop_index(op.f('ix_savings_deposits_id'), table_name='savings_deposits')
    op.drop_index(op.f('ix_savings_deposits_group_id'), table_name='savings_deposits')
    op.drop_table('savings_deposits')
    op.drop_index(op.f('ix_savings_members_id'), table_name='savings_members')
    op.drop_index(op.f('ix_savings_members_group_id'), table_name='savings_members')
    op.drop_table('savings_members')
    op.drop_index(op.f('ix_savings_groups_id'), table_name='savings_groups')
    op.drop_index(op.f('ix_savings_groups_company_id'), table_name='savings_groups')
    op.drop_table('savings_groups')
    # ### end Alembic commands ###
