"""add_company_id_to_users

Revision ID: e68629c68c60
Revises: 0007_add_manufacturing_tables
Create Date: 2026-09-25 13:22:20.782488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68629c68c60'
down_revision: Union[str, None] = '0007_add_manufacturing_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_company_id'), ['company_id'], unique=False)
        batch_op.create_foreign_key('fk_users_company_id_companies', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_company_id_companies', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_company_id'))
        batch_op.drop_column('company_id')
    # ### end Alembic commands ###
